name: ai-composiso - Backend Image
run-name: ai-composiso - Backend Image - ${{ github.run_number }} 🚀
on:
  push:
    branches:
      - main_deprecated
  pull_request:
    branches:
      - main_deprecated
jobs:
  Backend-Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: funy-z
          password: ${{ secrets.ORG_PAT_V2 }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/funy-z/ai-composiso-backend:latest
